version: '2'
services:
  # the postgres image auto runs the init script in docker-entrypoint-initdb.d
  postgres:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     POSTGRES_USER: app
     POSTGRES_PASSWORD: password123
  # web:
  #   build: ./server
  #   ports:
  #    - "1337:1337"
  #   volumes:
  #    - .:/usr/src/app
  #   depends_on:
  #     - postgres
  #   command: ["node", "./server"]